// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/(signed-in)/_layout.tsx";
import * as $1 from "./routes/(signed-in)/lists/[id]/index.tsx";
import * as $2 from "./routes/(signed-in)/lists/index.tsx";
import * as $3 from "./routes/(signed-in)/notes/index.tsx";
import * as $4 from "./routes/(signed-out)/signin/index.tsx";
import * as $5 from "./routes/_app.tsx";
import * as $6 from "./routes/_layout.tsx";
import * as $7 from "./routes/_middleware.ts";
import * as $8 from "./routes/api/events/items.ts";
import * as $9 from "./routes/api/events/lists.ts";
import * as $10 from "./routes/api/events/notes.ts";
import * as $11 from "./routes/api/item.ts";
import * as $12 from "./routes/api/list.ts";
import * as $13 from "./routes/api/note.ts";
import * as $14 from "./routes/auth/callback/[provider].ts";
import * as $15 from "./routes/auth/signin.ts";
import * as $16 from "./routes/auth/signout.ts";
import * as $17 from "./routes/index.tsx";
import * as $$0 from "./islands/Misc.tsx";
import * as $$1 from "./islands/OAuthOptions.tsx";
import * as $$2 from "./islands/item/Item.tsx";
import * as $$3 from "./islands/list/List.tsx";
import * as $$4 from "./islands/notes/Editor.tsx";

const manifest = {
  routes: {
    "./routes/(signed-in)/_layout.tsx": $0,
    "./routes/(signed-in)/lists/[id]/index.tsx": $1,
    "./routes/(signed-in)/lists/index.tsx": $2,
    "./routes/(signed-in)/notes/index.tsx": $3,
    "./routes/(signed-out)/signin/index.tsx": $4,
    "./routes/_app.tsx": $5,
    "./routes/_layout.tsx": $6,
    "./routes/_middleware.ts": $7,
    "./routes/api/events/items.ts": $8,
    "./routes/api/events/lists.ts": $9,
    "./routes/api/events/notes.ts": $10,
    "./routes/api/item.ts": $11,
    "./routes/api/list.ts": $12,
    "./routes/api/note.ts": $13,
    "./routes/auth/callback/[provider].ts": $14,
    "./routes/auth/signin.ts": $15,
    "./routes/auth/signout.ts": $16,
    "./routes/index.tsx": $17,
  },
  islands: {
    "./islands/Misc.tsx": $$0,
    "./islands/OAuthOptions.tsx": $$1,
    "./islands/item/Item.tsx": $$2,
    "./islands/list/List.tsx": $$3,
    "./islands/notes/Editor.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
